### ISSUE TITLE
Improve wallet configuration in config file

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/neofs-s3-gw#607]
Now

```yaml
wallet:
  passphrase: pass
address: NfgHwwTi3wHAS8aFAN243C5vGbkYDpqLHP
```

Proposal like in HTTP gateway
```yaml
wallet:
  path: /path/to/wallet.json
  address: NfgHwwTi3wHAS8aFAN243C5vGbkYDpqLHP
  passphrase: pass
```
