### ISSUE TITLE
Sometimes S3 gate with single peer fails with "no healthy client" error

### ISSUE THREAD

**Issue by vdomnich-yadro** [nspcc-dev/neofs-s3-gw#636]
## Steps to Reproduce (for bugs)
Assuming that you have all python modules from [testcases](https://github.com/nspcc-dev/neofs-testcases/pull/265).

You can run the following script and on some iteration of the loop you would observe Access Denied exception:
```
import os

import s3_gate_bucket
import wallet


ASSETS_DIR = "tmp"
os.makedirs(ASSETS_DIR, exist_ok=True)


def create_test_bucket(test_wallet: str) -> str:
    _, _, access_key_id, secret_access_key, _ = s3_gate_bucket.init_s3_credentials(
        test_wallet,
        s3_bearer_rules_file="robot/resources/files/s3_bearer_rules.json"
    )
    s3_client = s3_gate_bucket.config_s3_client(access_key_id, secret_access_key)
    bucket = s3_gate_bucket.create_bucket_s3(s3_client)
    return bucket


def main():
    test_wallet = wallet.init_wallet(ASSETS_DIR)
    for attempt in range(50):
        bucket = create_test_bucket(test_wallet)
        print(f"attempt #{attempt}: created bucket {bucket}")


if __name__ == "__main__":
    main()
```

After several iterations of the loop (typically 3-7 attempts) you will get an Access Denied error.
At the time of this error log of S3 gateway says: "no healthy client".

## Your Environment
Cloud VM with the following spec: 2 vCPU, 4GB RAM
The VM is hosting S3 gateway and storage node. Storage is configured to be free (no gas required).

S3 is configured to work against single peer and tree service:
```
peers:
  0:
    address: node1.neofs:8080
    priority: 1
    weight: 1
```

* Version used:
```
NEO-GO         - 0.99.1-pre-197-g68b5260f
NEOFS-CLI      - v0.30.0
NEOFS-AUTHMATE - v0.22.0
AWS            - 2.2.0
```

* Server setup and configuration:
```
  <project name="morph-crest.git"     revision="a915cb945b7571c6098a21185bba620f7e0516eb" />
  <project name="neo-go.git"          revision="68b5260fb5ed953fae6237dae781ba8baa4451da" />
  <project name="neo-preodolenie.git" revision="a6fb56b26392cf837940483d09dcc6db272d9427" upstream="master" />
  <project name="neofs-contract.git"  revision="fbc63cf0543209dcbb19414011df423f462a6d9e" upstream="refs/tags/v0.15.3" />
  <project name="neofs-http-gw.git"   revision="98991d63ae7ede4f51d0c2c51310e0cc37791356" upstream="refs/tags/v0.22.0" />
  <project name="neofs-locode-db.git" revision="ffd8516fccb63c9955f1d4202fb8f5b858188aa1" upstream="refs/tags/v0.2.1"  />
  <project name="neofs-node.git"      revision="2a1c5557f271828d9388db4de65d859f2fddb63f" upstream="refs/tags/v0.30.0" />
  <project name="neofs-s3-gw.git"     revision="618025c969deb61aba91d4c4074defd382e4daeb" upstream="refs/tags/v0.22.0" />
  ```

**Comment by vdomnich-yadro** [comment]
If we re-configure S3 gateway to run against multiple peers the problem goes away.
Sample config that allows to get rid of the error:
```
peers:
  0:
    address: node1.neofs:8080
    priority: 1
    weight: 1
  1:
    address: node2.neofs:8080
    priority: 2
    weight: 0.4
  2:
    address: node3.neofs:8080
    priority: 2
    weight: 0.3
  3:
    address: node4.neofs:8080
    priority: 2
    weight: 0.3
```
