### ISSUE TITLE
upload-part-copy doesn't create part because bucket/key not found

### ISSUE THREAD

**Issue by anikeev-yadro** [nspcc-dev/neofs-s3-gw#673]
**Steps to reproduce:**

1. Create source object
```
C:\TEMP>aws --no-verify-ssl s3api put-object --bucket b-test-lock-10 --key 'multipart-obj71' --body c:\TEMP\AWSCLIV2-download-p1.msi --endpoint-url http://172.26.163.38:8084
{
    "ETag": "54631d1173147c13e3c3c970ab19a449de07714ae6d1ec6f38a85bebdbf4f487"
}
```
2. Create multipartupload
```
C:\TEMP>aws s3api create-multipart-upload --bucket b-test-lock-10  --key 'multipart-obj70'  --endpoint-url http://172.26.163.38:8084
{
    "Bucket": "b-test-lock-10",
    "Key": "'multipart-obj70'",
    "UploadId": "aeb9bc9f-3a30-439d-af9a-894e150a1673"
}
```
3. Try to load source object as part of multipartupload. Parameter --copy-source expected value "bucket/object". Try to use parameter with quotes/without qoutes. As result the command not found bucket or key.
```
C:\TEMP>aws s3api upload-part-copy --bucket b-test-lock-10  --key 'multipart-obj70'  --endpoint-url http://172.26.163.38:8084 --upload-id aeb9bc9f-3a30-439d-af9a-894e150a1673 --part-number 1 --copy-source 'b-test-lock-10/multipart-obj71'

An error occurred (NoSuchBucket) when calling the UploadPartCopy operation: The specified bucket does not exist
```
```
C:\TEMP>aws s3api upload-part-copy --bucket b-test-lock-10  --key 'multipart-obj70'  --endpoint-url http://172.26.163.38:8084 --upload-id aeb9bc9f-3a30-439d-af9a-894e150a1673 --part-number 1 --copy-source b-test-lock-10/multipart-obj71

An error occurred (NoSuchKey) when calling the UploadPartCopy operation: The specified key does not exist.
```

**Logs:**
```
Aug 24 07:48:43 az neofs-s3-gw[5874]: 2022-08-24T07:48:43.833Z        debug        layer/layer.go:368        bucket not found        {"error": "failed resolve: couldn't resolve container ''b-test-lock-10': NNS contract fault exception: at instruction 5469 (THROW): unhandled exception: \"invalid domain name format\""}
Aug 24 07:48:43 az neofs-s3-gw[5874]: 2022-08-24T07:48:43.833Z        error        handler/util.go:25        could not get source bucket info        {"request_id": "2ab1181b-d834-4b8f-8a73-c9fc6068161e", "method": "UploadPartCopy", "bucket_name": "b-test-lock-10", "object_name": "'multipart-obj70'", "error": "NoSuchBucket: 404 => The specified bucket does not exist"}
Aug 24 07:48:43 az neofs-s3-gw[5874]: 2022-08-24T07:48:43.833Z        error        api/router.go:158        something went wrong        {"status": 404, "request_id": "2ab1181b-d834-4b8f-8a73-c9fc6068161e", "method": "UploadPartCopy", "description": "Not Found"}
```
```
Aug 24 07:50:53 az neofs-s3-gw[5874]: 2022-08-24T07:50:53.420Z        error        handler/util.go:25        could not head source object        {"request_id": "f2b54abf-4621-4279-86a8-02dd22b63f96", "method": "UploadPartCopy", "bucket_name": "b-test-lock-10", "object_name": "'multipart-obj70'", "error": "NoSuchKey: 404 => The specified key does not exist.", "uploadID": "aeb9bc9f-3a30-439d-af9a-894e150a1673", "Key": "'multipart-obj70'"}
Aug 24 07:50:53 az neofs-s3-gw[5874]: 2022-08-24T07:50:53.420Z        error        api/router.go:158        something went wrong        {"status": 404, "request_id": "f2b54abf-4621-4279-86a8-02dd22b63f96", "method": "UploadPartCopy", "description": "Not Found"}
```

**Product versions:**
```
s3 gateway
Version: v0.23.0-36-g3b343d1-dirty
GoVersion: go1.18.4

NeoFS Storage node
Version: v0.31.0
GoVersion: go1.18.4

NeoGo
Version: 0.99.1
GoVersion: go1.18.4
```
**s3 gateway config:**
```
default_policy: REP 1 IN X CBF 1 SELECT 1 FROM * AS X
listen_address: 0.0.0.0:8084
logger:
  level: debug
max_clients_count: 600
max_clients_deadline: 60s
peers:
  '0':
    address: node1.neofs:8080
    priority: '1'
    weight: '1'
  '1':
    address: node2.neofs:8080
    priority: '2'
    weight: '0.25'
  '2':
    address: node3.neofs:8080
    priority: '2'
    weight: '0.25'
  '3':
    address: node4.neofs:8080
    priority: '2'
    weight: '0.25'
pool_error_threshold: 100
pprof:
  address: localhost:8085
  enabled: true
prometheus:
  address: localhost:8086
  enabled: true
resolve_order:
- nns
rpc_endpoint: http://node1.neofs:40332
tree:
  service: 172.26.163.38:8080
wallet:
  address: ''
  passphrase: ''
  path: /etc/neofs/s3/wallet.json
```
