### ISSUE TITLE
put-object-acl doesn't change actual ACL

### ISSUE THREAD

**Issue by anikeev-yadro** [nspcc-dev/neofs-s3-gw#676]
**Steps to reproduce:**

1. Create bucket with public-read-write ACL
```
PS C:\temp> aws --no-verify-ssl s3api create-bucket --bucket b-test-lock-20 --endpoint-url http://172.26.163.38:8084 --object-lock-enabled-for-bucket --acl public-read-write
PS C:\temp> aws --no-verify-ssl s3api get-bucket-acl --bucket b-test-lock-20 --endpoint-url http://172.26.163.38:8084
{
    "Owner": {
        "DisplayName": "NS9iuCpxq8VzpKWLSwceguV5pz2YAYtG6M",
        "ID": "NS9iuCpxq8VzpKWLSwceguV5pz2YAYtG6M"
    },
    "Grants": [
        {
            "Grantee": {
                "Type": "Group",
                "URI": "http://acs.amazonaws.com/groups/global/AllUsers"
            },
            "Permission": "FULL_CONTROL"
        },
        {
            "Grantee": {
                "ID": "02efc49d370eb40238b85d8469439b5dd70dac7b1567aaf251eef311a312098b13",
                "Type": "CanonicalUser"
            },
            "Permission": "FULL_CONTROL"
        }
    ]
}
```
2. Create source object
```
PS C:\temp> aws --no-verify-ssl s3api put-object --bucket b-test-lock-20 --key multipart-obj80 --body c:\TEMP\AWSCLIV2.msi --endpoint-url http://172.26.163.38:8084
{
    "ETag": "00370046e346ca9f6e377f20b02f7c96b9a7230ff7c9d7af9a5fb96db4368b83",
    "VersionId": "C2sa6PVZ9mxi2JEojN5hG67ek9fvnNKo9CKXKcViiMqj"
}

PS C:\temp> aws --no-verify-ssl s3api get-object-acl --bucket b-test-lock-20 --key multipart-obj80  --endpoint-url http://172.26.163.38:8084
{
    "Owner": {
        "DisplayName": "NS9iuCpxq8VzpKWLSwceguV5pz2YAYtG6M",
        "ID": "NS9iuCpxq8VzpKWLSwceguV5pz2YAYtG6M"
    },
    "Grants": []
}
```
3. Put public-read-write ACL to object
```
PS C:\temp> aws --no-verify-ssl s3api put-object-acl --bucket b-test-lock-20 --key multipart-obj80  --endpoint-url http://172.26.163.38:8084 --acl public-read-write
```
4. But ACL was not changed
```
PS C:\temp> aws --no-verify-ssl s3api get-object-acl --bucket b-test-lock-20 --key multipart-obj80  --endpoint-url http://172.26.163.38:8084
{
    "Owner": {
        "DisplayName": "NS9iuCpxq8VzpKWLSwceguV5pz2YAYtG6M",
        "ID": "NS9iuCpxq8VzpKWLSwceguV5pz2YAYtG6M"
    },
    "Grants": []
}
```

**Logs:**
```
Aug 24 12:41:50 az neofs-s3-gw[5874]: 2022-08-24T12:41:50.641Z        info        api/router.go:167        call method        {"status": 200, "request_id": "35be4892-d198-4708-a00a-0b51cb29393f", "method": "PutObjectACL", "description": "OK"}
```

**Product versions:**
```
s3 gateway
Version: v0.23.0-36-g3b343d1-dirty
GoVersion: go1.18.4

NeoFS Storage node
Version: v0.31.0
GoVersion: go1.18.4

NeoGo
Version: 0.99.1
GoVersion: go1.18.4
```

**s3 gateway config:**
```
default_policy: REP 1 IN X CBF 1 SELECT 1 FROM * AS X
listen_address: 0.0.0.0:8084
logger:
  level: debug
max_clients_count: 600
max_clients_deadline: 60s
peers:
  '0':
    address: node1.neofs:8080
    priority: '1'
    weight: '1'
  '1':
    address: node2.neofs:8080
    priority: '2'
    weight: '0.25'
  '2':
    address: node3.neofs:8080
    priority: '2'
    weight: '0.25'
  '3':
    address: node4.neofs:8080
    priority: '2'
    weight: '0.25'
pool_error_threshold: 100
pprof:
  address: localhost:8085
  enabled: true
prometheus:
  address: localhost:8086
  enabled: true
resolve_order:
- nns
rpc_endpoint: http://node1.neofs:40332
tree:
  service: 172.26.163.38:8080
wallet:
  address: ''
  passphrase: ''
  path: /etc/neofs/s3/wallet.json
```
