### ISSUE TITLE
s3-gateway doesn't work correctly with containers created from neo-cli

### ISSUE THREAD

**Issue by anikeev-yadro** [nspcc-dev/neofs-s3-gw#701]
**Steps to reproduce:**

1.Create container
```
anikeev@NB-1670:~/neofs$ sudo ./neofs-cli --rpc-endpoint 172.26.160.212:8080 --wallet wallet.json container create --name f_test_1 --policy "REP 2 IN X CBF 1 SELECT 4 FROM * AS X" --await
Enter password >
container ID: BhtWQfs3R6vgakEhbtRYvqsTXswMfaV6gGWJbECJQ5vd
awaiting...
container has been persisted on sidechain
```
2. See it from s3
```
PS C:\TEMP> aws --no-verify-ssl s3api list-buckets  --endpoint-url http://172.26.160.212:8084
{
    "Buckets": [
            "Name": "f_test_1",
            "CreationDate": "2022-09-06T10:56:03+00:00"
        },
    ],
    "Owner": {
        "DisplayName": "NS9iuCpxq8VzpKWLSwceguV5pz2YAYtG6M",
        "ID": "NS9iuCpxq8VzpKWLSwceguV5pz2YAYtG6M"
    }
}
```
3. But we cannot do anything with it:
```
PS C:\TEMP> aws --no-verify-ssl s3api list-objects --bucket f_test_1 --endpoint-url http://172.26.160.212:8084
An error occurred (InternalError) when calling the ListObjects operation (reached max retries: 2): failed to get sub tree: rpc error: code = Unknown desc = database not open

PS C:\TEMP> aws --no-verify-ssl s3api put-object --bucket f_test_1 --key obj20 --body c:\TEMP\AWSCLIV2-download-p1.msi --endpoint-url http://172.26.160.212:8084
An error occurred (NoSuchBucket) when calling the PutObject operation: The specified bucket does not exist

PS C:\TEMP> aws --no-verify-ssl s3api head-bucket --bucket f_test_1 --endpoint-url http://172.26.160.212:8084
An error occurred (404) when calling the HeadBucket operation: Not Found
```

**Errors in logs:**
```
сен 06 11:21:59 az neofs-s3-gw[647]: 2022-09-06T11:21:59.228Z        debug        layer/layer.go:371        bucket not found        {"error": "failed resolve: couldn't resolve container 'f_test_1': NNS contract fault exception: at instruction 5469 (THROW): unhandled exception: \"invalid domain name format\""}
сен 06 11:21:59 az neofs-s3-gw[647]: 2022-09-06T11:21:59.229Z        error        handler/util.go:25        could not get bucket info        {"request_id": "d93cc854-be60-4dc2-a2fd-cb87ce8ffb2d", "method": "GetBucketACL", "bucket_name": "f_test_1", "object_name": "", "error": "NoSuchBucket: 404 => The specified bucket does not exist"}
сен 06 11:21:59 az neofs-s3-gw[647]: 2022-09-06T11:21:59.229Z        error        api/router.go:158        something went wrong        {"status": 404, "request_id": "d93cc854-be60-4dc2-a2fd-cb87ce8ffb2d", "method": "GetBucketACL", "description": "Not Found"}
```

4. Try to use CID instead of bucket name:
```
PS C:\TEMP> aws --no-verify-ssl s3api get-bucket-acl --bucket BhtWQfs3R6vgakEhbtRYvqsTXswMfaV6gGWJbECJQ5vd --endpoint-url http://172.26.160.212:8084
An error occurred (InternalError) when calling the GetBucketAcl operation (reached max retries: 2): get container eacl: read eACL via connection pool: get eacl on client: status: code = 3073 message = eACL not found
```
**Errors in logs:**
```
сен 06 12:09:31 az neofs-s3-gw[647]: 2022-09-06T12:09:31.408Z        error        handler/util.go:25        could not fetch bucket acl        {"request_id": "1ac48a5d-544a-4217-9751-6d52d0903663", "method": "GetBucketACL", "bucket_name": "BhtWQfs3R6vgakEhbtRYvqsTXswMfaV6gGWJbECJQ5vd", "object_name": "", "error": "get container eacl: read eACL via connection pool: get eacl on client: status: code = 3073 message = eACL not found"}
сен 06 12:09:31 az neofs-s3-gw[647]: 2022-09-06T12:09:31.408Z        error        api/router.go:158        something went wrong        {"status": 500, "request_id": "1ac48a5d-544a-4217-9751-6d52d0903663", "method": "GetBucketACL", "description": "Internal Server Error"}
сен 06 12:09:31 az neofs-s3-gw[647]: 2022-09-06T12:09:31.858Z        error        handler/util.go:25        could not fetch bucket acl        {"request_id": "2398ac88-567e-4aec-a593-c95115c9e15f", "method": "GetBucketACL", "bucket_name": "BhtWQfs3R6vgakEhbtRYvqsTXswMfaV6gGWJbECJQ5vd", "object_name": "", "error": "get container eacl: read eACL via connection pool: get eacl on client: status: code = 3073 message = eACL not found"}
сен 06 12:09:31 az neofs-s3-gw[647]: 2022-09-06T12:09:31.858Z        error        api/router.go:158        something went wrong        {"status": 500, "request_id": "2398ac88-567e-4aec-a593-c95115c9e15f", "method": "GetBucketACL", "description": "Internal Server Error"}
сен 06 12:09:32 az neofs-s3-gw[647]: 2022-09-06T12:09:32.036Z        error        handler/util.go:25        could not fetch bucket acl        {"request_id": "8fb5445f-4223-44f4-8c49-9ad02a2f072e", "method": "GetBucketACL", "bucket_name": "BhtWQfs3R6vgakEhbtRYvqsTXswMfaV6gGWJbECJQ5vd", "object_name": "", "error": "get container eacl: read eACL via connection pool: get eacl on client: status: code = 3073 message = eACL not found"}
сен 06 12:09:32 az neofs-s3-gw[647]: 2022-09-06T12:09:32.036Z        error        api/router.go:158        something went wrong        {"status": 500, "request_id": "8fb5445f-4223-44f4-8c49-9ad02a2f072e", "method": "GetBucketACL", "description": "Internal Server Error"}
```
5. Another try to use CID instead of bucket name:
```
PS C:\TEMP> aws --no-verify-ssl s3api head-bucket --bucket BhtWQfs3R6vgakEhbtRYvqsTXswMfaV6gGWJbECJQ5vd --endpoint-url http://172.26.160.212:8084
PS C:\TEMP> aws --no-verify-ssl s3api put-object --bucket BhtWQfs3R6vgakEhbtRYvqsTXswMfaV6gGWJbECJQ5vd --key obj20 --body c:\TEMP\AWSCLIV2-download-p1.msi --endpoint-url http://172.26.160.212:8084
An error occurred (InternalError) when calling the PutObject operation (reached max retries: 2): couldn't get node: couldn't get nodes: failed to get node path: rpc error: code = Unknown desc = database not open
```

**Product versions:**
```
s3 gateway
Version: v0.23.0-60-g272c485
GoVersion: go1.18.4

NeoFS Storage node
Version: v0.31.0-66-gd8a00c36
GoVersion: go1.18.4

NeoGo
Version: 0.99.2-2-g536303ef
GoVersion: go1.18.4
```
**s3 gateway config:**
```
default_policy: REP 1 IN X CBF 1 SELECT 1 FROM * AS X
listen_address: 0.0.0.0:8084
logger:
  level: debug
max_clients_count: 600
max_clients_deadline: 60s
peers:
  '0':
    address: node1.neofs:8080
    priority: '1'
    weight: '1'
  '1':
    address: node2.neofs:8080
    priority: '2'
    weight: '0.25'
  '2':
    address: node3.neofs:8080
    priority: '2'
    weight: '0.25'
  '3':
    address: node4.neofs:8080
    priority: '2'
    weight: '0.25'
pool_error_threshold: 100
pprof:
  address: localhost:8085
  enabled: true
prometheus:
  address: localhost:8086
  enabled: true
resolve_order:
- nns
rpc_endpoint: http://node1.neofs:40332
tree:
  service: 172.26.160.212:8080
wallet:
  address: ''
  passphrase: ''
  path: /etc/neofs/s3/wallet.json
```
