### ISSUE TITLE
Put object with object-lock-legal-hold-status ON doesn't work

### ISSUE THREAD

**Issue by dansingjulia** [nspcc-dev/neofs-s3-gw#709]
1. Try to put new object into bucket **without parameter object-lock-legal-hold-status:**

```
Executing command: aws --no-verify-ssl --no-paginate s3api put-object --bucket 427ba77e-1c2b-4619-a4ae-6aca30f6f174 --key ce524392-1e52-4df9-bf4e-6b178fba7149 --body /home/yulia/dev/neofs-testcases/TemporaryDir/ce524392-1e52-4df9-bf4e-6b178fba7149 --endpoint http://172.26.160.106:8084 --object-lock-mode GOVERNANCE --object-lock-retain-until-date "2022-09-16T13:37:38"
Output: {
    "ETag": "05f393e12068ef2883933964b0259146c67177541e4827017f3e76304b513921",
    "VersionId": "DLsjj9t337J2UfhLrHsu3u5FK8r5KFPjRwvSouzBqaw7"
}
```
it's work. and parameters is disable:
```
Executing command: aws --no-verify-ssl --no-paginate s3api get-object --bucket 427ba77e-1c2b-4619-a4ae-6aca30f6f174 --key ce524392-1e52-4df9-bf4e-6b178fba7149  TemporaryDir//6d468e98-1e4e-4152-a32c-e158e60a1109 --endpoint http://172.26.160.106:8084
Output: {
    "LastModified": "2022-09-15T10:43:47+00:00",
    "ContentLength": 2000,
    "ETag": "05f393e12068ef2883933964b0259146c67177541e4827017f3e76304b513921",
    "VersionId": "DLsjj9t337J2UfhLrHsu3u5FK8r5KFPjRwvSouzBqaw7",
    "ContentType": "application/octet-stream",
    "Metadata": {},
    "TagCount": 0,
    "ObjectLockMode": "GOVERNANCE",
    "ObjectLockRetainUntilDate": "2022-09-16T13:37:38+00:00",
    "ObjectLockLegalHoldStatus": "OFF"
}
```

2. Try to put **with object-lock-legal-hold-status = OFF**:
```
Executing command:  aws --no-verify-ssl --no-paginate s3api put-object --bucket 427ba77e-1c2b-4619-a4ae-6aca30f6f174 --key 38b1c6b9-f96f-4884-bd36-a45854a02485 --body /home/yulia/dev/neofs-testcases/TemporaryDir/38b1c6b9-f96f-4884-bd36-a45854a02485 --endpoint http://172.26.160.106:8084 --object-lock-mode GOVERNANCE --object-lock-retain-until-date "2022-09-16T13:37:38" --object-lock-legal-hold-status OFF
{
    "ETag": "fc96effd84fc0f0a6503b1485c70adaeb06d2a8f0e5a555816b7abb8823721b4",
    "VersionId": "74En8H3A2K32sscrMntFmf8frcN15WvqKBapUaGsgHmM"
}
```
it's works correctly: 
```
Executing command: aws --no-verify-ssl --no-paginate s3api get-object --bucket 427ba77e-1c2b-4619-a4ae-6aca30f6f174 --key 38b1c6b9-f96f-4884-bd36-a45854a02485  TemporaryDir//ce847e87-2f12-49ea-b4bb-e552918cc5eb --endpoint http://172.26.160.106:8084
2022-09-15 13:40:49 [INFO] Output: {
    "LastModified": "2022-09-15T10:38:22+00:00",
    "ContentLength": 2000,
    "ETag": "fc96effd84fc0f0a6503b1485c70adaeb06d2a8f0e5a555816b7abb8823721b4",
    "VersionId": "97vZ2WNbVUPdJhXurbpzta3N3GSSd786rPrMzjV2hsQx",
    "ContentType": "application/octet-stream",
    "Metadata": {},
    "TagCount": 0,
    "ObjectLockMode": "GOVERNANCE",
    "ObjectLockRetainUntilDate": "2022-09-16T13:37:38+00:00",
    "ObjectLockLegalHoldStatus": "OFF"
}
```
3. Try to put **with object-lock-legal-hold-status = ON:**
```
Executing command:  aws --no-verify-ssl --no-paginate s3api put-object --bucket 427ba77e-1c2b-4619-a4ae-6aca30f6f174 --key 38b1c6b9-f96f-4884-bd36-a45854a02485 --body /home/yulia/dev/neofs-testcases/TemporaryDir/38b1c6b9-f96f-4884-bd36-a45854a02485 --endpoint http://172.26.160.106:8084 --object-lock-mode GOVERNANCE --object-lock-retain-until-date "2022-09-16T13:37:38" --object-lock-legal-hold-status ON

An error occurred (InternalError) when calling the PutObject operation (reached max retries: 0): save object via connection pool: init writing on API client: client failure: status: code = 1024 message = missing expiration epoch attribute
```
**Expected reult: Put object with object-lock-legal-hold-status = ON
Actual result: An error occurred (InternalError)** 

**Product versions:**
```
admin@az:~$ neofs-s3-gw --version
NeoFS S3 Gateway
Version: v0.23.0-73-g67b01a30
GoVersion: go1.18.4


NeoFS CLI
Version: v0.31.0-109-g0140ac35-dirty
GoVersion: go1.19 

admin@az:~$ neofs-storage -v
-bash: neofs-storage: команда не найдена
admin@az:~$ neofs-node --version
NeoFS Storage node

((local-pytest)) yulia@nb-1833:~/dev/neofs-testcases$ aws --version
aws-cli/2.7.29 Python/3.9.11 Linux/5.10.16.3-microsoft-standard-WSL2 exe/x86_64.ubuntu.20 prompt/off
```
**s3 gateway config:**

```
default_policy: REP 1 IN X CBF 1 SELECT 1 FROM * AS X
listen_address: 0.0.0.0:8084
logger:
  level: debug
max_clients_count: 600
max_clients_deadline: 60s
peers:
  '0':
    address: node1.neofs:8080
    priority: '1'
    weight: '1'
  '1':
    address: node2.neofs:8080
    priority: '2'
    weight: '0.25'
  '2':
    address: node3.neofs:8080
    priority: '2'
    weight: '0.25'
  '3':
    address: node4.neofs:8080
    priority: '2'
    weight: '0.25'
pool_error_threshold: 100
pprof:
  address: localhost:8085
  enabled: true
prometheus:
  address: localhost:8086
  enabled: true
resolve_order:
- nns
rpc_endpoint: http://node1.neofs:40332
tree:
  service: 172.26.160.106:8080
wallet:
  address: ''
  passphrase: ''
  path: /etc/neofs/s3/wallet.json
```

**logs:**
[log_for_bug.log](https://github.com/nspcc-dev/neofs-s3-gw/files/9582867/log_for_bug.log)
[test_log.txt](https://github.com/nspcc-dev/neofs-s3-gw/files/9582868/test_log.txt)
